### ISSUE TITLE
Devels / Forms some are corrupted

### ISSUE THREAD

**Issue by gael-seroul** [3dem/emhub#109]
Hi,
Using the docker installation when I click on Devel / Forms I can see what forms look like clicking on the eye icon. But all config forms have error doing this:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/emhub/__init__.py", line 347, in get_content
    kwargs = app.dc.get(**content_kwargs)
  File "/usr/local/lib/python3.8/site-packages/emhub/data/content/dc_base.py", line 73, in get
    dataDict.update(get_func(**kwargs))
  File "/usr/local/lib/python3.8/site-packages/emhub/data/content/dc_base.py", line 79, in wrapper
    return func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/emhub/data/content/dc_raw.py", line 126, in dynamic_form_modal
    return dc.dynamic_form(form, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/emhub/data/content/dc_base.py", line 129, in dynamic_form
    self.set_form_values(form, form_values)
  File "/usr/local/lib/python3.8/site-packages/emhub/data/content/dc_base.py", line 112, in set_form_values
    for section in definition['sections']:
KeyError: 'sections'

**Comment by delarosatrevin** [comment]
The "config" forms are not meant to be displayed—only those with parameters definition, where they are expected. I updated the devel branch, and now, the eye icon does not appear in the list for the config forms.
