### ISSUE TITLE
Reset password error

### ISSUE THREAD

**Issue by gael-seroul** [3dem/emhub#110]
I tried the devel branch new fix for reset password. When I click on Reset Password button I get these error in my console:

gunicorn -k gevent --workers=2 'emhub:create_app()' --bind 0.0.0.0:8899
[2024-12-16 12:04:56 +0100] [4271] [INFO] Starting gunicorn 21.2.0
[2024-12-16 12:04:56 +0100] [4271] [INFO] Listening at: http://0.0.0.0:8899 (4271)
[2024-12-16 12:04:56 +0100] [4271] [INFO] Using worker: gevent
[2024-12-16 12:04:56 +0100] [4272] [INFO] Booting worker with pid: 4272
[2024-12-16 12:04:56 +0100] [4273] [INFO] Booting worker with pid: 4273
[2024-12-16 12:05:15,284] ERROR in app: Exception on /reset_password_request [POST]
Traceback (most recent call last):
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/crims/cryoEM/dev/emhub/emhub/__init__.py", line 305, in reset_password_request
    token = user.get_reset_password_token()
  File "/home/crims/cryoEM/dev/emhub/emhub/data/data_models.py", line 260, in get_reset_password_token
    token = jwt.encode(
AttributeError: 'str' object has no attribute 'decode'

**Comment by delarosatrevin** [comment]
Thanks a lot for reporting this!

It is fixed now in devel. The error came from a different behavior of the PyJWT library for versions > 2.0.0.
