### ISSUE TITLE
user does not see Profile page

### ISSUE THREAD

**Issue by gael-seroul** [3dem/emhub#111]
As admin I can see page Profile (clicking top right user button). As user I get an error:

Request failed: error 

ERROR in app: Exception on /get_content [POST]
Traceback (most recent call last):
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/crims/cryoEM/dev/emhub/emhub/__init__.py", line 373, in get_content
    return flask.render_template(content_template, **kwargs)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/crims/cryoEM/dev/emhub/emhub/templates/user_profile.html", line 33, in top-level template code
    <h3 class="font-16 pl-3">{{ head_label }}</h3> <a class="pl-3" href="javascript:showUser({{ head['id'] }})">{{ head['name'] }}</a>
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element 0

**Comment by delarosatrevin** [comment]
Did you generate the test instance in the devel branch?

Anyway, the error is likely because there is no user with the role "head." can you try to make one the head and check if the error is solved?

I will check this and handle the case better with or without the "head" defined.

**Comment by gael-seroul** [comment]
Hi, I used the created instance from main branch first.
I tried to create a test instance from the devel branch:
emh-data --create_instance /home/crims/cryoEM/emhub-data-dev/ emhub/data/imports/test_instance_data.json
New instance was created in /home/crims/cryoEM/emhub-data-dev/ but when I start using:
gunicorn -k gevent --workers=2 'emhub:create_app()' --bind 0.0.0.0:8899
It create folder /home/crims/cryoEM/emhub-data-dev/emhub-instance/  and I guess emhub application is using this folder, but nothing is working.
If I check /home/crims/cryoEM/emhub-data-dev/emhub.sqlite data are OK, But the new instance /home/crims/cryoEM/emhub-data-dev/emhub-instance/emhub.sqlite is empty.

Did I do something wrong ?
Thanks for your help

**Comment by delarosatrevin** [comment]
Have you set the EMHUB_INSTANCE variable to the proper location before running gunicorn? That variable specifies where the instance data (data, folder, etc.) is. If it does not exist, emhub will create an empty one.

**Comment by gael-seroul** [comment]
I think:
echo $EMHUB_INSTANCE
/home/crims/cryoEM/emhub-data-dev/

Is it normal that the new created folder (using create_instance) contains emhub.sqlite, but when running the application (devel with gunicorn or main in docker) it creates a folder below => emhub-instance ?  Or maybe I have something wrong in a conf somewhere, but this happens with my 2 installation.

**Comment by delarosatrevin** [comment]
Yes, the value is OK. No, it is not expected that it will create it again. How are you biding the instance folder when running docker? Depending on that, you might need to specify a different value for the EMHUB_INSTANCE inside the docker running container. Can you debug using a conda environment with EMhub installed instead of docker?

**Comment by gael-seroul** [comment]
I tried again from scratch and it works like it should, sorry I should had some wrong conf somewhere. Using admin account I created a user but then when logged in still error when clicking on profile menu

[2024-12-17 17:18:25,486] ERROR in app: Exception on /get_content [POST]
Traceback (most recent call last):
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/crims/cryoEM/dev/emhub/emhub/__init__.py", line 373, in get_content
    return flask.render_template(content_template, **kwargs)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/crims/cryoEM/dev/emhub/emhub/templates/user_profile.html", line 33, in top-level template code
    <h3 class="font-16 pl-3">{{ head_label }}</h3> <a class="pl-3" href="javascript:showUser({{ head['id'] }})">{{ head['name'] }}</a>
  File "/home/crims/miniforge3/envs/emhub/lib/python3.9/site-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element 0

**Comment by delarosatrevin** [comment]
Ok, we made some progress. I was able to reproduce your error. It is because you didn't assign a PI to the user. Users should be:
- staff (with manager and staff roles)
- PI (with pi role)
- lab members (where a pi should be assigned)

I will add some validations to clarify these requirements and try to avoid these inconsistent states.
