### ISSUE TITLE
error generating test data

### ISSUE THREAD

**Issue by azazellochg** [3dem/emhub#64]
```
(emhub) gsharov@hal:~/soft/emhub$ python -m emhub.data
Populating forms...
Populating users...
Populating resources...
Populating applications...
Populating bookings...
Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/emhub/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/public/EM/Scipion/miniconda3/envs/emhub/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/lmb/home/gsharov/soft/emhub/emhub/data/__main__.py", line 35, in <module>
TestData(dm)
File "/lmb/home/gsharov/soft/emhub/emhub/data/imports/__init__.py", line 45, in __init__
self._populateTestData(dm)
File "/lmb/home/gsharov/soft/emhub/emhub/data/imports/__init__.py", line 58, in _populateTestData
self._populateBookings(dm)
File "/lmb/home/gsharov/soft/emhub/emhub/data/imports/test.py", line 273, in _populateBookings
dm.create_booking(title='',
File "/lmb/home/gsharov/soft/emhub/emhub/data/data_manager.py", line 325, in create_booking
_add_booking(attrs)
File "/lmb/home/gsharov/soft/emhub/emhub/data/data_manager.py", line 319, in _add_booking
b = self.__create_booking(attrs,
File "/lmb/home/gsharov/soft/emhub/emhub/data/data_manager.py", line 948, in __create_booking
self.__validate_booking(b, **kwargs)
File "/lmb/home/gsharov/soft/emhub/emhub/data/data_manager.py", line 1028, in __validate_booking
raise Exception("User %s has no active application"
Exception: User Rick Shaw has no active application
```

**Comment by delarosatrevin** [comment]
I think the test data has been outdated....I took a look and there are some missing pieces. I will check it later with more time and update it. Thanks for checking this.
